// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxf8kyc8seuIZpqmsRNcyPHgP7d9ykq3w',
    appId: '1:856735068586:web:ba459827dca91bb424fbd3',
    messagingSenderId: '856735068586',
    projectId: 'mamashay-9b77e',
    authDomain: 'mamashay-9b77e.firebaseapp.com',
    storageBucket: 'mamashay-9b77e.appspot.com',
    measurementId: 'G-QYGN51H785',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC9W2i7S_BcNv15jmVFXo1u_TtmeXN4vk',
    appId: '1:856735068586:android:c421c5de52b8f8da24fbd3',
    messagingSenderId: '856735068586',
    projectId: 'mamashay-9b77e',
    storageBucket: 'mamashay-9b77e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDag8C9ITPYyRU1PemdrcGKSEjJ5Xx0pSI',
    appId: '1:856735068586:ios:71eed51bff77f69524fbd3',
    messagingSenderId: '856735068586',
    projectId: 'mamashay-9b77e',
    storageBucket: 'mamashay-9b77e.appspot.com',
    iosBundleId: 'com.example.mamashay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDag8C9ITPYyRU1PemdrcGKSEjJ5Xx0pSI',
    appId: '1:856735068586:ios:71eed51bff77f69524fbd3',
    messagingSenderId: '856735068586',
    projectId: 'mamashay-9b77e',
    storageBucket: 'mamashay-9b77e.appspot.com',
    iosBundleId: 'com.example.mamashay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxf8kyc8seuIZpqmsRNcyPHgP7d9ykq3w',
    appId: '1:856735068586:web:69d0d60ba37e573624fbd3',
    messagingSenderId: '856735068586',
    projectId: 'mamashay-9b77e',
    authDomain: 'mamashay-9b77e.firebaseapp.com',
    storageBucket: 'mamashay-9b77e.appspot.com',
    measurementId: 'G-FPVYNHNQZ8',
  );
}
